### ISSUE TITLE
Deliver Shipyrd gem as a Docker image

### ISSUE THREAD

**Issue by AliOsm** [Shipyrd/shipyrd-gem#11]
Using Shipyrd in non-Ruby projects requires Ruby to be installed to make sure the Kamal hooks are able to ping Shipyrd server. I thought about delivering Shipyrd gem as a Docker image similar to Kamal gem. If you think it is useful, I can discover the approach more.

**Comment by nickhammond** [comment]
Hey @AliOsm,

That's probably the best approach for now instead of building packages for the various languages/platforms. If you'd like to explore it go for it! Some great starting points in the kamal repo too.

**Comment by nickhammond** [comment]
@AliOsm Thanks for this! I just cut [v0.2.8](https://github.com/Shipyrd/shipyrd-gem/releases/tag/v0.2.8) with this.
